//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization;

[assembly: ContractNamespace("http://www.mi9retail.com/WCFServices/", ClrNamespace = "www.mi9retail.com.WCFServices")]

namespace QuickSilver.Core.Services.wcf
{
// 
// This code was auto-generated by slsvcutil, version 4.0.60310.0
// 
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsRequest", Namespace = "http://www.mi9retail.com/WCFServices/")]
    [KnownType(typeof(clsRequestWithPayloadOfstring))]
    public partial class clsRequest : object
    {

        private string PasswordField;

        private bool PasswordEncryptedField;

        private int RequestIDField;

        private System.Guid SessionIDField;

        private string TerminalField;

        private System.DateTime TimestampField;

        private string TrancodeField;

        private string UserField;

        private decimal VersionField;

        [DataMember()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }

        [DataMember()]
        public bool PasswordEncrypted
        {
            get
            {
                return this.PasswordEncryptedField;
            }
            set
            {
                this.PasswordEncryptedField = value;
            }
        }

        [DataMember()]
        public int RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }

        [DataMember()]
        public System.Guid SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }

        [DataMember()]
        public string Terminal
        {
            get
            {
                return this.TerminalField;
            }
            set
            {
                this.TerminalField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }

        [DataMember()]
        public string Trancode
        {
            get
            {
                return this.TrancodeField;
            }
            set
            {
                this.TrancodeField = value;
            }
        }

        [DataMember()]
        public string User
        {
            get
            {
                return this.UserField;
            }
            set
            {
                this.UserField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public decimal Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsRequestWithPayloadOfstring", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsRequestWithPayloadOfstring : clsRequest
    {

        private string PayloadField;

        [DataMember(IsRequired = true)]
        public string Payload
        {
            get
            {
                return this.PayloadField;
            }
            set
            {
                this.PayloadField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsResponse", Namespace = "http://www.mi9retail.com/WCFServices/")]
    [KnownType(typeof(clsResponseWithErrorAndResultOfboolean))]
    [KnownType(typeof(clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ))]
    [KnownType(typeof(clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ))]
    [KnownType(typeof(clsResponseWithResultOfbase64Binary))]
    public partial class clsResponse : object
    {

        private string InstallationInstanceNameField;

        private int RequestIDField;

        private string ServerNameField;

        private System.Guid SessionIDField;

        private System.DateTime TimestampField;

        private decimal VersionField;

        [DataMember()]
        public string InstallationInstanceName
        {
            get
            {
                return this.InstallationInstanceNameField;
            }
            set
            {
                this.InstallationInstanceNameField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public int RequestID
        {
            get
            {
                return this.RequestIDField;
            }
            set
            {
                this.RequestIDField = value;
            }
        }

        [DataMember()]
        public string ServerName
        {
            get
            {
                return this.ServerNameField;
            }
            set
            {
                this.ServerNameField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public System.Guid SessionID
        {
            get
            {
                return this.SessionIDField;
            }
            set
            {
                this.SessionIDField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.TimestampField;
            }
            set
            {
                this.TimestampField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public decimal Version
        {
            get
            {
                return this.VersionField;
            }
            set
            {
                this.VersionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsResponseWithErrorAndResultOfboolean", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsResponseWithErrorAndResultOfboolean : clsResponse
    {

        private string ErrorField;

        private bool ResultField;

        [DataMember()]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public bool Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ : clsResponse
    {

        private StoreReportInfo[] ResultField;

        [DataMember(IsRequired = true)]
        public StoreReportInfo[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ : clsResponse
    {

        private CompanyReportInfo[] ResultField;

        [DataMember(IsRequired = true)]
        public CompanyReportInfo[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsResponseWithResultOfbase64Binary", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsResponseWithResultOfbase64Binary : clsResponse
    {

        private byte[] ResultField;

        [DataMember(IsRequired = true)]
        public byte[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "StoreReportInfo", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class StoreReportInfo : ReportInfo
    {
        private string Address1Field;

        private string Address2Field;

        private string Address3Field;

        private string Address4Field;

        private string Address5Field;

        private string CountryField;

        private string FaxField;

        private bool IsForAllStoresField;

        private decimal LatitudeField;

        private string LeagueCodeField;

        private string LeagueDescriptionField;

        private string Level1CodeField;

        private string Level1DescriptionField;

        private string Level2CodeField;

        private string Level2DescriptionField;

        private string Level3CodeField;

        private string Level3DescriptionField;

        private string Level4CodeField;

        private string Level4DescriptionField;

        private string Level5CodeField;

        private string Level5DescriptionField;

        private decimal LongitudeField;

        private string PostCodeField;

        private string StoreCodeField;

        private string StoreDescriptionField;

        private int StoreIDField;

        private string Telephone1Field;

        private string Telephone2Field;

        [DataMember()]
        public string Address1
        {
            get
            {
                return this.Address1Field;
            }
            set
            {
                this.Address1Field = value;
            }
        }

        [DataMember()]
        public string Address2
        {
            get
            {
                return this.Address2Field;
            }
            set
            {
                this.Address2Field = value;
            }
        }

        [DataMember()]
        public string Address3
        {
            get
            {
                return this.Address3Field;
            }
            set
            {
                this.Address3Field = value;
            }
        }

        [DataMember()]
        public string Address4
        {
            get
            {
                return this.Address4Field;
            }
            set
            {
                this.Address4Field = value;
            }
        }

        [DataMember()]
        public string Address5
        {
            get
            {
                return this.Address5Field;
            }
            set
            {
                this.Address5Field = value;
            }
        }

        [DataMember()]
        public string Country
        {
            get
            {
                return this.CountryField;
            }
            set
            {
                this.CountryField = value;
            }
        }

        [DataMember()]
        public string Fax
        {
            get
            {
                return this.FaxField;
            }
            set
            {
                this.FaxField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public bool IsForAllStores
        {
            get
            {
                return this.IsForAllStoresField;
            }
            set
            {
                this.IsForAllStoresField = value;
            }
        }

        [DataMember()]
        public decimal Latitude
        {
            get
            {
                return this.LatitudeField;
            }
            set
            {
                this.LatitudeField = value;
            }
        }

        [DataMember()]
        public string LeagueCode
        {
            get
            {
                return this.LeagueCodeField;
            }
            set
            {
                this.LeagueCodeField = value;
            }
        }

        [DataMember()]
        public string LeagueDescription
        {
            get
            {
                return this.LeagueDescriptionField;
            }
            set
            {
                this.LeagueDescriptionField = value;
            }
        }

        [DataMember()]
        public string Level1Code
        {
            get
            {
                return this.Level1CodeField;
            }
            set
            {
                this.Level1CodeField = value;
            }
        }

        [DataMember()]
        public string Level1Description
        {
            get
            {
                return this.Level1DescriptionField;
            }
            set
            {
                this.Level1DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level2Code
        {
            get
            {
                return this.Level2CodeField;
            }
            set
            {
                this.Level2CodeField = value;
            }
        }

        [DataMember()]
        public string Level2Description
        {
            get
            {
                return this.Level2DescriptionField;
            }
            set
            {
                this.Level2DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level3Code
        {
            get
            {
                return this.Level3CodeField;
            }
            set
            {
                this.Level3CodeField = value;
            }
        }

        [DataMember()]
        public string Level3Description
        {
            get
            {
                return this.Level3DescriptionField;
            }
            set
            {
                this.Level3DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level4Code
        {
            get
            {
                return this.Level4CodeField;
            }
            set
            {
                this.Level4CodeField = value;
            }
        }

        [DataMember()]
        public string Level4Description
        {
            get
            {
                return this.Level4DescriptionField;
            }
            set
            {
                this.Level4DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level5Code
        {
            get
            {
                return this.Level5CodeField;
            }
            set
            {
                this.Level5CodeField = value;
            }
        }

        [DataMember()]
        public string Level5Description
        {
            get
            {
                return this.Level5DescriptionField;
            }
            set
            {
                this.Level5DescriptionField = value;
            }
        }

        [DataMember()]
        public decimal Longitude
        {
            get
            {
                return this.LongitudeField;
            }
            set
            {
                this.LongitudeField = value;
            }
        }

        [DataMember()]
        public string PostCode
        {
            get
            {
                return this.PostCodeField;
            }
            set
            {
                this.PostCodeField = value;
            }
        }

        [DataMember()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }

        [DataMember()]
        public string StoreDescription
        {
            get
            {
                return this.StoreDescriptionField;
            }
            set
            {
                this.StoreDescriptionField = value;
            }
        }

        [DataMember()]
        public int StoreID
        {
            get
            {
                return this.StoreIDField;
            }
            set
            {
                this.StoreIDField = value;
            }
        }

        [DataMember()]
        public string Telephone1
        {
            get
            {
                return this.Telephone1Field;
            }
            set
            {
                this.Telephone1Field = value;
            }
        }

        [DataMember()]
        public string Telephone2
        {
            get
            {
                return this.Telephone2Field;
            }
            set
            {
                this.Telephone2Field = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "ReportInfo", Namespace = "http://www.mi9retail.com/WCFServices/")]
    [KnownType(typeof(CompanyReportInfo))]
    [KnownType(typeof(StoreReportInfo))]
    public partial class ReportInfo : object
    {

        private System.DateTime CreateDateTimeUTCField;

        private string FilenameField;

        private string ReportCodeField;

        private string ReportDescriptionField;

        private int SizeInKBField;

        [DataMember(IsRequired = true)]
        public System.DateTime CreateDateTimeUTC
        {
            get
            {
                return this.CreateDateTimeUTCField;
            }
            set
            {
                this.CreateDateTimeUTCField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public string Filename
        {
            get
            {
                return this.FilenameField;
            }
            set
            {
                this.FilenameField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public string ReportCode
        {
            get
            {
                return this.ReportCodeField;
            }
            set
            {
                this.ReportCodeField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public string ReportDescription
        {
            get
            {
                return this.ReportDescriptionField;
            }
            set
            {
                this.ReportDescriptionField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public int SizeInKB
        {
            get
            {
                return this.SizeInKBField;
            }
            set
            {
                this.SizeInKBField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "CompanyReportInfo", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class CompanyReportInfo : ReportInfo
    {

        private int CompanyHierarchyIDField;

        private byte CompanyHierarchyLevelField;

        private bool IsForEntireCompanyField;

        private string Level1CodeField;

        private string Level1DescriptionField;

        private string Level2CodeField;

        private string Level2DescriptionField;

        private string Level3CodeField;

        private string Level3DescriptionField;

        private string Level4CodeField;

        private string Level4DescriptionField;

        private string Level5CodeField;

        private string Level5DescriptionField;

        [DataMember()]
        public int CompanyHierarchyID
        {
            get
            {
                return this.CompanyHierarchyIDField;
            }
            set
            {
                this.CompanyHierarchyIDField = value;
            }
        }

        [DataMember()]
        public byte CompanyHierarchyLevel
        {
            get
            {
                return this.CompanyHierarchyLevelField;
            }
            set
            {
                this.CompanyHierarchyLevelField = value;
            }
        }

        [DataMember(IsRequired = true)]
        public bool IsForEntireCompany
        {
            get
            {
                return this.IsForEntireCompanyField;
            }
            set
            {
                this.IsForEntireCompanyField = value;
            }
        }

        [DataMember()]
        public string Level1Code
        {
            get
            {
                return this.Level1CodeField;
            }
            set
            {
                this.Level1CodeField = value;
            }
        }

        [DataMember()]
        public string Level1Description
        {
            get
            {
                return this.Level1DescriptionField;
            }
            set
            {
                this.Level1DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level2Code
        {
            get
            {
                return this.Level2CodeField;
            }
            set
            {
                this.Level2CodeField = value;
            }
        }

        [DataMember()]
        public string Level2Description
        {
            get
            {
                return this.Level2DescriptionField;
            }
            set
            {
                this.Level2DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level3Code
        {
            get
            {
                return this.Level3CodeField;
            }
            set
            {
                this.Level3CodeField = value;
            }
        }

        [DataMember()]
        public string Level3Description
        {
            get
            {
                return this.Level3DescriptionField;
            }
            set
            {
                this.Level3DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level4Code
        {
            get
            {
                return this.Level4CodeField;
            }
            set
            {
                this.Level4CodeField = value;
            }
        }

        [DataMember()]
        public string Level4Description
        {
            get
            {
                return this.Level4DescriptionField;
            }
            set
            {
                this.Level4DescriptionField = value;
            }
        }

        [DataMember()]
        public string Level5Code
        {
            get
            {
                return this.Level5CodeField;
            }
            set
            {
                this.Level5CodeField = value;
            }
        }

        [DataMember()]
        public string Level5Description
        {
            get
            {
                return this.Level5DescriptionField;
            }
            set
            {
                this.Level5DescriptionField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsAuthenticationFault", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsAuthenticationFault : object
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsBaseFault", Namespace = "http://www.mi9retail.com/WCFServices/")]
    [KnownType(typeof(clsUserDoesNotHavePermissionFault))]
    [KnownType(typeof(clsParameterNotProvidedFault))]
    public partial class clsBaseFault : object
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsUserDoesNotHavePermissionFault", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsUserDoesNotHavePermissionFault : clsBaseFault
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [DataContract(Name = "clsParameterNotProvidedFault", Namespace = "http://www.mi9retail.com/WCFServices/")]
    public partial class clsParameterNotProvidedFault : clsBaseFault
    {
    }


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.mi9retail.com/WCFServices/", ConfigurationName = "IRetailHubContract")]
    public interface IRetailHubContract
    {

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://www.mi9retail.com/WCFServices/BaseService/Authenticate", ReplyAction = "http://www.mi9retail.com/WCFServices/BaseService/AuthenticateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsAuthenticationFault), Action = "http://www.mi9retail.com/WCFServices/BaseService/AuthenticateclsAuthenticationFau" +
                                                                                                                           "ltFault", Name = "clsAuthenticationFault")]
        System.IAsyncResult BeginAuthenticate(clsRequest InRequest, System.AsyncCallback callback, object asyncState);

        clsResponse EndAuthenticate(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/PostInventoryChanges", ReplyAction = "http://www.mi9retail.com/WCFServices/IRetailHubContract/PostInventoryChangesRespo" +
                                                                                                                                                                                    "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsParameterNotProvidedFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/PostInventoryChangesclsPa" +
                                                                                                                                 "rameterNotProvidedFaultFault", Name = "clsParameterNotProvidedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsUserDoesNotHavePermissionFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/PostInventoryChangesclsUs" +
                                                                                                                                      "erDoesNotHavePermissionFaultFault", Name = "clsUserDoesNotHavePermissionFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsAuthenticationFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/PostInventoryChangesclsAu" +
                                                                                                                           "thenticationFaultFault", Name = "clsAuthenticationFault")]
        System.IAsyncResult BeginPostInventoryChanges(clsRequestWithPayloadOfstring InRequest, System.AsyncCallback callback, object asyncState);

        clsResponseWithErrorAndResultOfboolean EndPostInventoryChanges(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableStoreRe" +
                                                                                      "portsForUser", ReplyAction = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableStoreRe" +
                                                                                                                    "portsForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsAuthenticationFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableStoreRe" +
                                                                                                                           "portsForUserclsAuthenticationFaultFault", Name = "clsAuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsParameterNotProvidedFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableStoreRe" +
                                                                                                                                 "portsForUserclsParameterNotProvidedFaultFault", Name = "clsParameterNotProvidedFault")]
        System.IAsyncResult BeginGetListOfAvailableStoreReportsForUser(clsRequest InRequest, System.AsyncCallback callback, object asyncState);

        clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ EndGetListOfAvailableStoreReportsForUser(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableCoStruc" +
                                                                                      "tureReportsForUser", ReplyAction = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableCoStruc" +
                                                                                                                          "tureReportsForUserResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsAuthenticationFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableCoStruc" +
                                                                                                                           "tureReportsForUserclsAuthenticationFaultFault", Name = "clsAuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsParameterNotProvidedFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetListOfAvailableCoStruc" +
                                                                                                                                 "tureReportsForUserclsParameterNotProvidedFaultFault", Name = "clsParameterNotProvidedFault")]
        System.IAsyncResult BeginGetListOfAvailableCoStructureReportsForUser(clsRequest InRequest, System.AsyncCallback callback, object asyncState);

        clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ EndGetListOfAvailableCoStructureReportsForUser(System.IAsyncResult result);

        [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetReport", ReplyAction = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsParameterNotProvidedFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetReportclsParameterNotP" +
                                                                                                                                 "rovidedFaultFault", Name = "clsParameterNotProvidedFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(clsAuthenticationFault), Action = "http://www.mi9retail.com/WCFServices/IRetailHubContract/GetReportclsAuthenticatio" +
                                                                                                                           "nFaultFault", Name = "clsAuthenticationFault")]
        System.IAsyncResult BeginGetReport(clsRequestWithPayloadOfstring InRequest, System.AsyncCallback callback, object asyncState);

        clsResponseWithResultOfbase64Binary EndGetReport(System.IAsyncResult result);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRetailHubContractChannel : IRetailHubContract, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenticateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public AuthenticateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public clsResponse Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((clsResponse)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostInventoryChangesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public PostInventoryChangesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public clsResponseWithErrorAndResultOfboolean Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((clsResponseWithErrorAndResultOfboolean)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListOfAvailableStoreReportsForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetListOfAvailableStoreReportsForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetListOfAvailableCoStructureReportsForUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetListOfAvailableCoStructureReportsForUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetReportCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        public GetReportCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        public clsResponseWithResultOfbase64Binary Result
        {
            get
            {
                base.RaiseExceptionIfNecessary();
                return ((clsResponseWithResultOfbase64Binary)(this.results[0]));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RetailHubContractClient : System.ServiceModel.ClientBase<IRetailHubContract>, IRetailHubContract
    {

        private BeginOperationDelegate onBeginAuthenticateDelegate;

        private EndOperationDelegate onEndAuthenticateDelegate;

        private System.Threading.SendOrPostCallback onAuthenticateCompletedDelegate;

        private BeginOperationDelegate onBeginPostInventoryChangesDelegate;

        private EndOperationDelegate onEndPostInventoryChangesDelegate;

        private System.Threading.SendOrPostCallback onPostInventoryChangesCompletedDelegate;

        private BeginOperationDelegate onBeginGetListOfAvailableStoreReportsForUserDelegate;

        private EndOperationDelegate onEndGetListOfAvailableStoreReportsForUserDelegate;

        private System.Threading.SendOrPostCallback onGetListOfAvailableStoreReportsForUserCompletedDelegate;

        private BeginOperationDelegate onBeginGetListOfAvailableCoStructureReportsForUserDelegate;

        private EndOperationDelegate onEndGetListOfAvailableCoStructureReportsForUserDelegate;

        private System.Threading.SendOrPostCallback onGetListOfAvailableCoStructureReportsForUserCompletedDelegate;

        private BeginOperationDelegate onBeginGetReportDelegate;

        private EndOperationDelegate onEndGetReportDelegate;

        private System.Threading.SendOrPostCallback onGetReportCompletedDelegate;

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        public RetailHubContractClient()
        {
        }

        public RetailHubContractClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public RetailHubContractClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public RetailHubContractClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public RetailHubContractClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                                                               "ookieContainerBindingElement.");
                }
            }
        }

        public event System.EventHandler<AuthenticateCompletedEventArgs> AuthenticateCompleted;

        public event System.EventHandler<PostInventoryChangesCompletedEventArgs> PostInventoryChangesCompleted;

        public event System.EventHandler<GetListOfAvailableStoreReportsForUserCompletedEventArgs> GetListOfAvailableStoreReportsForUserCompleted;

        public event System.EventHandler<GetListOfAvailableCoStructureReportsForUserCompletedEventArgs> GetListOfAvailableCoStructureReportsForUserCompleted;

        public event System.EventHandler<GetReportCompletedEventArgs> GetReportCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRetailHubContract.BeginAuthenticate(clsRequest InRequest, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginAuthenticate(InRequest, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clsResponse IRetailHubContract.EndAuthenticate(System.IAsyncResult result)
        {
            return base.Channel.EndAuthenticate(result);
        }

        private System.IAsyncResult OnBeginAuthenticate(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            clsRequest InRequest = ((clsRequest)(inValues[0]));
            return ((IRetailHubContract)(this)).BeginAuthenticate(InRequest, callback, asyncState);
        }

        private object[] OnEndAuthenticate(System.IAsyncResult result)
        {
            clsResponse retVal = ((IRetailHubContract)(this)).EndAuthenticate(result);
            return new object[] {
                                    retVal};
        }

        private void OnAuthenticateCompleted(object state)
        {
            if ((this.AuthenticateCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AuthenticateCompleted(this, new AuthenticateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void AuthenticateAsync(clsRequest InRequest)
        {
            this.AuthenticateAsync(InRequest, null);
        }

        public void AuthenticateAsync(clsRequest InRequest, object userState)
        {
            if ((this.onBeginAuthenticateDelegate == null))
            {
                this.onBeginAuthenticateDelegate = new BeginOperationDelegate(this.OnBeginAuthenticate);
            }
            if ((this.onEndAuthenticateDelegate == null))
            {
                this.onEndAuthenticateDelegate = new EndOperationDelegate(this.OnEndAuthenticate);
            }
            if ((this.onAuthenticateCompletedDelegate == null))
            {
                this.onAuthenticateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAuthenticateCompleted);
            }
            base.InvokeAsync(this.onBeginAuthenticateDelegate, new object[] {
                                                                                InRequest}, this.onEndAuthenticateDelegate, this.onAuthenticateCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRetailHubContract.BeginPostInventoryChanges(clsRequestWithPayloadOfstring InRequest, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginPostInventoryChanges(InRequest, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clsResponseWithErrorAndResultOfboolean IRetailHubContract.EndPostInventoryChanges(System.IAsyncResult result)
        {
            return base.Channel.EndPostInventoryChanges(result);
        }

        private System.IAsyncResult OnBeginPostInventoryChanges(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            clsRequestWithPayloadOfstring InRequest = ((clsRequestWithPayloadOfstring)(inValues[0]));
            return ((IRetailHubContract)(this)).BeginPostInventoryChanges(InRequest, callback, asyncState);
        }

        private object[] OnEndPostInventoryChanges(System.IAsyncResult result)
        {
            clsResponseWithErrorAndResultOfboolean retVal = ((IRetailHubContract)(this)).EndPostInventoryChanges(result);
            return new object[] {
                                    retVal};
        }

        private void OnPostInventoryChangesCompleted(object state)
        {
            if ((this.PostInventoryChangesCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.PostInventoryChangesCompleted(this, new PostInventoryChangesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void PostInventoryChangesAsync(clsRequestWithPayloadOfstring InRequest)
        {
            this.PostInventoryChangesAsync(InRequest, null);
        }

        public void PostInventoryChangesAsync(clsRequestWithPayloadOfstring InRequest, object userState)
        {
            if ((this.onBeginPostInventoryChangesDelegate == null))
            {
                this.onBeginPostInventoryChangesDelegate = new BeginOperationDelegate(this.OnBeginPostInventoryChanges);
            }
            if ((this.onEndPostInventoryChangesDelegate == null))
            {
                this.onEndPostInventoryChangesDelegate = new EndOperationDelegate(this.OnEndPostInventoryChanges);
            }
            if ((this.onPostInventoryChangesCompletedDelegate == null))
            {
                this.onPostInventoryChangesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnPostInventoryChangesCompleted);
            }
            base.InvokeAsync(this.onBeginPostInventoryChangesDelegate, new object[] {
                                                                                        InRequest}, this.onEndPostInventoryChangesDelegate, this.onPostInventoryChangesCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRetailHubContract.BeginGetListOfAvailableStoreReportsForUser(clsRequest InRequest, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetListOfAvailableStoreReportsForUser(InRequest, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ IRetailHubContract.EndGetListOfAvailableStoreReportsForUser(System.IAsyncResult result)
        {
            return base.Channel.EndGetListOfAvailableStoreReportsForUser(result);
        }

        private System.IAsyncResult OnBeginGetListOfAvailableStoreReportsForUser(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            clsRequest InRequest = ((clsRequest)(inValues[0]));
            return ((IRetailHubContract)(this)).BeginGetListOfAvailableStoreReportsForUser(InRequest, callback, asyncState);
        }

        private object[] OnEndGetListOfAvailableStoreReportsForUser(System.IAsyncResult result)
        {
            clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ retVal = ((IRetailHubContract)(this)).EndGetListOfAvailableStoreReportsForUser(result);
            return new object[] {
                                    retVal};
        }

        private void OnGetListOfAvailableStoreReportsForUserCompleted(object state)
        {
            if ((this.GetListOfAvailableStoreReportsForUserCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListOfAvailableStoreReportsForUserCompleted(this, new GetListOfAvailableStoreReportsForUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetListOfAvailableStoreReportsForUserAsync(clsRequest InRequest)
        {
            this.GetListOfAvailableStoreReportsForUserAsync(InRequest, null);
        }

        public void GetListOfAvailableStoreReportsForUserAsync(clsRequest InRequest, object userState)
        {
            if ((this.onBeginGetListOfAvailableStoreReportsForUserDelegate == null))
            {
                this.onBeginGetListOfAvailableStoreReportsForUserDelegate = new BeginOperationDelegate(this.OnBeginGetListOfAvailableStoreReportsForUser);
            }
            if ((this.onEndGetListOfAvailableStoreReportsForUserDelegate == null))
            {
                this.onEndGetListOfAvailableStoreReportsForUserDelegate = new EndOperationDelegate(this.OnEndGetListOfAvailableStoreReportsForUser);
            }
            if ((this.onGetListOfAvailableStoreReportsForUserCompletedDelegate == null))
            {
                this.onGetListOfAvailableStoreReportsForUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListOfAvailableStoreReportsForUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetListOfAvailableStoreReportsForUserDelegate, new object[] {
                                                                                                         InRequest}, this.onEndGetListOfAvailableStoreReportsForUserDelegate, this.onGetListOfAvailableStoreReportsForUserCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRetailHubContract.BeginGetListOfAvailableCoStructureReportsForUser(clsRequest InRequest, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetListOfAvailableCoStructureReportsForUser(InRequest, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ IRetailHubContract.EndGetListOfAvailableCoStructureReportsForUser(System.IAsyncResult result)
        {
            return base.Channel.EndGetListOfAvailableCoStructureReportsForUser(result);
        }

        private System.IAsyncResult OnBeginGetListOfAvailableCoStructureReportsForUser(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            clsRequest InRequest = ((clsRequest)(inValues[0]));
            return ((IRetailHubContract)(this)).BeginGetListOfAvailableCoStructureReportsForUser(InRequest, callback, asyncState);
        }

        private object[] OnEndGetListOfAvailableCoStructureReportsForUser(System.IAsyncResult result)
        {
            clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ retVal = ((IRetailHubContract)(this)).EndGetListOfAvailableCoStructureReportsForUser(result);
            return new object[] {
                                    retVal};
        }

        private void OnGetListOfAvailableCoStructureReportsForUserCompleted(object state)
        {
            if ((this.GetListOfAvailableCoStructureReportsForUserCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetListOfAvailableCoStructureReportsForUserCompleted(this, new GetListOfAvailableCoStructureReportsForUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetListOfAvailableCoStructureReportsForUserAsync(clsRequest InRequest)
        {
            this.GetListOfAvailableCoStructureReportsForUserAsync(InRequest, null);
        }

        public void GetListOfAvailableCoStructureReportsForUserAsync(clsRequest InRequest, object userState)
        {
            if ((this.onBeginGetListOfAvailableCoStructureReportsForUserDelegate == null))
            {
                this.onBeginGetListOfAvailableCoStructureReportsForUserDelegate = new BeginOperationDelegate(this.OnBeginGetListOfAvailableCoStructureReportsForUser);
            }
            if ((this.onEndGetListOfAvailableCoStructureReportsForUserDelegate == null))
            {
                this.onEndGetListOfAvailableCoStructureReportsForUserDelegate = new EndOperationDelegate(this.OnEndGetListOfAvailableCoStructureReportsForUser);
            }
            if ((this.onGetListOfAvailableCoStructureReportsForUserCompletedDelegate == null))
            {
                this.onGetListOfAvailableCoStructureReportsForUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetListOfAvailableCoStructureReportsForUserCompleted);
            }
            base.InvokeAsync(this.onBeginGetListOfAvailableCoStructureReportsForUserDelegate, new object[] {
                                                                                                               InRequest}, this.onEndGetListOfAvailableCoStructureReportsForUserDelegate, this.onGetListOfAvailableCoStructureReportsForUserCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult IRetailHubContract.BeginGetReport(clsRequestWithPayloadOfstring InRequest, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetReport(InRequest, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        clsResponseWithResultOfbase64Binary IRetailHubContract.EndGetReport(System.IAsyncResult result)
        {
            return base.Channel.EndGetReport(result);
        }

        private System.IAsyncResult OnBeginGetReport(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            clsRequestWithPayloadOfstring InRequest = ((clsRequestWithPayloadOfstring)(inValues[0]));
            return ((IRetailHubContract)(this)).BeginGetReport(InRequest, callback, asyncState);
        }

        private object[] OnEndGetReport(System.IAsyncResult result)
        {
            clsResponseWithResultOfbase64Binary retVal = ((IRetailHubContract)(this)).EndGetReport(result);
            return new object[] {
                                    retVal};
        }

        private void OnGetReportCompleted(object state)
        {
            if ((this.GetReportCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetReportCompleted(this, new GetReportCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetReportAsync(clsRequestWithPayloadOfstring InRequest)
        {
            this.GetReportAsync(InRequest, null);
        }

        public void GetReportAsync(clsRequestWithPayloadOfstring InRequest, object userState)
        {
            if ((this.onBeginGetReportDelegate == null))
            {
                this.onBeginGetReportDelegate = new BeginOperationDelegate(this.OnBeginGetReport);
            }
            if ((this.onEndGetReportDelegate == null))
            {
                this.onEndGetReportDelegate = new EndOperationDelegate(this.OnEndGetReport);
            }
            if ((this.onGetReportCompletedDelegate == null))
            {
                this.onGetReportCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetReportCompleted);
            }
            base.InvokeAsync(this.onBeginGetReportDelegate, new object[] {
                                                                             InRequest}, this.onEndGetReportDelegate, this.onGetReportCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync()
        {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync()
        {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        protected override IRetailHubContract CreateChannel()
        {
            return new RetailHubContractClientChannel(this);
        }

        private class RetailHubContractClientChannel : ChannelBase<IRetailHubContract>, IRetailHubContract
        {

            public RetailHubContractClientChannel(System.ServiceModel.ClientBase<IRetailHubContract> client) :
                base(client)
            {
            }

            public System.IAsyncResult BeginAuthenticate(clsRequest InRequest, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = InRequest;
                System.IAsyncResult _result = base.BeginInvoke("Authenticate", _args, callback, asyncState);
                return _result;
            }

            public clsResponse EndAuthenticate(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                clsResponse _result = ((clsResponse)(base.EndInvoke("Authenticate", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginPostInventoryChanges(clsRequestWithPayloadOfstring InRequest, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = InRequest;
                System.IAsyncResult _result = base.BeginInvoke("PostInventoryChanges", _args, callback, asyncState);
                return _result;
            }

            public clsResponseWithErrorAndResultOfboolean EndPostInventoryChanges(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                clsResponseWithErrorAndResultOfboolean _result = ((clsResponseWithErrorAndResultOfboolean)(base.EndInvoke("PostInventoryChanges", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetListOfAvailableStoreReportsForUser(clsRequest InRequest, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = InRequest;
                System.IAsyncResult _result = base.BeginInvoke("GetListOfAvailableStoreReportsForUser", _args, callback, asyncState);
                return _result;
            }

            public clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ EndGetListOfAvailableStoreReportsForUser(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ _result = ((clsResponseWithResultOfArrayOfStoreReportInfoMoVubBOZ)(base.EndInvoke("GetListOfAvailableStoreReportsForUser", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetListOfAvailableCoStructureReportsForUser(clsRequest InRequest, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = InRequest;
                System.IAsyncResult _result = base.BeginInvoke("GetListOfAvailableCoStructureReportsForUser", _args, callback, asyncState);
                return _result;
            }

            public clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ EndGetListOfAvailableCoStructureReportsForUser(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ _result = ((clsResponseWithResultOfArrayOfCompanyReportInfoMoVubBOZ)(base.EndInvoke("GetListOfAvailableCoStructureReportsForUser", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginGetReport(clsRequestWithPayloadOfstring InRequest, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = InRequest;
                System.IAsyncResult _result = base.BeginInvoke("GetReport", _args, callback, asyncState);
                return _result;
            }

            public clsResponseWithResultOfbase64Binary EndGetReport(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                clsResponseWithResultOfbase64Binary _result = ((clsResponseWithResultOfbase64Binary)(base.EndInvoke("GetReport", _args, result)));
                return _result;
            }
        }
    }
}